### ISSUE TITLE
Error in call syntax for S_RF, T_RF, X_RF

### ISSUE THREAD

**Issue by jain-nikunj** [soerenkuenzel/acic_reproduction_code#1]
As per changes in the `causalToolbox` package, the parameters of `mtry` and `splitratio` when passed into the `S_RF` and `T_RF` estimators are no longer directly passed in. They are instead passed in as elements of a list which is passed as an argument under the `mu.forestry` (or `mu0.forestry` and `mu1.forestry` for `T_RF`) parameter. A similar issue exists for parameters passed to `X_RF`.
The issue manifests when running the file `acic_reproduction_code/1-IndividualLevel/1_03_create_estimator_outputCT.R` file. The cause of the issue is defined in `acic_reproduction_code/1-IndividualLevel/1_02_define_estimator_outputCT.R` file when defining  `estimator_grid` on line 42.

Until this is fixed, direct reproduction of results is not possible.

**Comment by soerenkuenzel** [comment]
Thanks for flagging this. That is true. We have improved `causalToolbox` and some of the functions are now called differently. I have changed it and it should be fixed now with the most recent fix. Please let me know, if it still does not run.
